Importing the libraries

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importing the data

In [54]:
train  = pd.read_csv('/content/train.csv')
train.head()

id  Mean_Integrated         SD        EK  Skewness  Mean_DMSNR_Curve  \
0   0       133.171875  59.716081  0.043133 -0.703383         54.917224   
1   1        87.093750  36.257973  0.435469  2.266057          3.417224   
2   2       112.640625  39.818393  0.379639  0.922306          2.730769   
3   3       120.679688  45.918448 -0.098490  0.011775          2.696488   
4   4       134.070312  57.720107 -0.107772 -0.573335          1.107860   

   SD_DMSNR_Curve  EK_DMSNR_Curve  Skewness_DMSNR_Curve  Class  
0       70.084438        0.749798             -0.649512      0  
1       21.865069        7.039330             52.686251      0  
2       15.689690        8.193471             85.649785      0  
3       20.954662        8.183874             70.332899      0  
4       11.255051       16.107748            308.753765      0

In [55]:
test  = pd.read_csv('/content/test.csv')
test.head()

id  Mean_Integrated         SD        EK  Skewness  Mean_DMSNR_Curve  \
0  117564       140.046875  54.507800  0.058862 -0.567263          2.337793   
1  117565       107.828125  51.578965  0.284368 -0.338430          1.574415   
2  117566       135.062500  49.812343 -0.087784 -0.094341          3.576923   
3  117567       112.812500  41.926647  0.519921  1.287762          6.669732   
4  117568        96.210938  35.322620  0.481286  2.443080          2.218227   

   SD_DMSNR_Curve  EK_DMSNR_Curve  Skewness_DMSNR_Curve  
0       14.868335        9.591760            117.988781  
1       12.501437       11.694968            182.704822  
2       21.243336        7.252386             59.021499  
3       29.013153        5.097661             27.105240  
4       17.041064        9.766006            117.131775

In [56]:
train.describe()

id  Mean_Integrated             SD             EK  \
count  117564.000000    117564.000000  117564.000000  117564.000000   
mean    58781.500000       111.248300      46.713535       0.503498   
std     33937.947861        24.906474       6.102941       1.127093   
min         0.000000         6.054688      24.783273      -1.730782   
25%     29390.750000       104.546875      43.443390       0.049761   
50%     58781.500000       116.664062      47.478932       0.186498   
75%     88172.250000       126.296875      50.862718       0.395620   
max    117563.000000       189.367188      93.602933       7.879628   

            Skewness  Mean_DMSNR_Curve  SD_DMSNR_Curve  EK_DMSNR_Curve  \
count  117564.000000     117564.000000   117564.000000   117564.000000   
mean        1.886385         11.962921       26.190678        8.037488   
std         6.515466         26.719946       20.041937        3.840980   
min        -1.791886          0.213211        7.370432       -2.597872   
25%        -0.188956          2.090301       14.955405        6.742911   
50%         0.091720          2.808528       18.164924        8.442883   
75%         0.691613          4.122910       24.732218       10.003237   
max        65.385974        217.371238      109.890785       34.539844   

       Skewness_DMSNR_Curve          Class  
count         117564.000000  117564.000000  
mean              93.881076       0.093285  
std               79.962110       0.290833  
min               -1.976976       0.000000  
25%               49.409136       0.000000  
50%               83.421375       0.000000  
75%              122.093290       0.000000  
max             1191.000837       1.000000

In [57]:
train['Class'].unique()

array([0, 1])

In [58]:
train.isnull().sum()

id                      0
Mean_Integrated         0
SD                      0
EK                      0
Skewness                0
Mean_DMSNR_Curve        0
SD_DMSNR_Curve          0
EK_DMSNR_Curve          0
Skewness_DMSNR_Curve    0
Class                   0
dtype: int64

In [59]:
test.isnull().sum()

id                      0
Mean_Integrated         0
SD                      0
EK                      0
Skewness                0
Mean_DMSNR_Curve        0
SD_DMSNR_Curve          0
EK_DMSNR_Curve          0
Skewness_DMSNR_Curve    0
dtype: int64

In [60]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117564 entries, 0 to 117563
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   id                    117564 non-null  int64  
 1   Mean_Integrated       117564 non-null  float64
 2   SD                    117564 non-null  float64
 3   EK                    117564 non-null  float64
 4   Skewness              117564 non-null  float64
 5   Mean_DMSNR_Curve      117564 non-null  float64
 6   SD_DMSNR_Curve        117564 non-null  float64
 7   EK_DMSNR_Curve        117564 non-null  float64
 8   Skewness_DMSNR_Curve  117564 non-null  float64
 9   Class                 117564 non-null  int64  
dtypes: float64(8), int64(2)
memory usage: 9.0 MB


In [61]:
test_id = test.iloc[:,0]

In [62]:
test_id = test_id.astype(int)

In [63]:
train.drop('id',axis=1,inplace=True)
test.drop('id',axis=1,inplace=True)

In [64]:
train.head()

Mean_Integrated         SD        EK  Skewness  Mean_DMSNR_Curve  \
0       133.171875  59.716081  0.043133 -0.703383         54.917224   
1        87.093750  36.257973  0.435469  2.266057          3.417224   
2       112.640625  39.818393  0.379639  0.922306          2.730769   
3       120.679688  45.918448 -0.098490  0.011775          2.696488   
4       134.070312  57.720107 -0.107772 -0.573335          1.107860   

   SD_DMSNR_Curve  EK_DMSNR_Curve  Skewness_DMSNR_Curve  Class  
0       70.084438        0.749798             -0.649512      0  
1       21.865069        7.039330             52.686251      0  
2       15.689690        8.193471             85.649785      0  
3       20.954662        8.183874             70.332899      0  
4       11.255051       16.107748            308.753765      0

In [65]:
test.head()

Mean_Integrated         SD        EK  Skewness  Mean_DMSNR_Curve  \
0       140.046875  54.507800  0.058862 -0.567263          2.337793   
1       107.828125  51.578965  0.284368 -0.338430          1.574415   
2       135.062500  49.812343 -0.087784 -0.094341          3.576923   
3       112.812500  41.926647  0.519921  1.287762          6.669732   
4        96.210938  35.322620  0.481286  2.443080          2.218227   

   SD_DMSNR_Curve  EK_DMSNR_Curve  Skewness_DMSNR_Curve  
0       14.868335        9.591760            117.988781  
1       12.501437       11.694968            182.704822  
2       21.243336        7.252386             59.021499  
3       29.013153        5.097661             27.105240  
4       17.041064        9.766006            117.131775

In [66]:
#train.dropna(subset = ['Class'])

In [67]:
x_train = train.iloc[:,0:-1].values

In [68]:

y_train = train.iloc[:,8].values


In [69]:
x_train

array([[ 1.33171875e+02,  5.97160815e+01,  4.31329240e-02, ...,
         7.00844376e+01,  7.49797994e-01, -6.49512056e-01],
       [ 8.70937500e+01,  3.62579733e+01,  4.35468922e-01, ...,
         2.18650690e+01,  7.03933030e+00,  5.26862514e+01],
       [ 1.12640625e+02,  3.98183935e+01,  3.79638726e-01, ...,
         1.56896904e+01,  8.19347104e+00,  8.56497849e+01],
       ...,
       [ 1.19757812e+02,  4.99800131e+01,  6.44015080e-02, ...,
         1.97885592e+01,  6.95974013e+00,  5.63677886e+01],
       [ 1.05789062e+02,  4.69865952e+01,  4.41426486e-01, ...,
         1.71706118e+01,  9.44244492e+00,  9.90745394e+01],
       [ 1.13515625e+02,  5.09359561e+01,  3.15166910e-02, ...,
         6.20068416e+01,  2.38636423e+00,  4.00185934e+00]])

In [70]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
test = scaler.transform(test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
lr = LogisticRegression()

In [77]:
lr.fit(x_train,y_train)

LogisticRegression()

In [72]:
#from sklearn.ensemble import RandomForestClassifier
#clf = RandomForestClassifier(random_state=0)

In [73]:
#clf.fit(x_train,y_train)

In [74]:
#predict = clf.predict(test)

In [78]:
predict = lr.predict(test)

In [79]:
submission = pd.DataFrame(data = {'id':test_id , 'Class':predict}, index=None)

In [80]:
submission

id  Class
0      117564      0
1      117565      0
2      117566      0
3      117567      0
4      117568      0
...       ...    ...
78372  195936      0
78373  195937      0
78374  195938      0
78375  195939      0
78376  195940      1

[78377 rows x 2 columns]

In [81]:
submission.to_csv('submission.csv', index=None)